version: '3.8'

services:
  postgres:
    image: postgres:13 # PostgreSQL image
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"  # Maps PostgreSQL's default port to your host
    environment:
      POSTGRES_USER: user          # Replace with your desired username
      POSTGRES_PASSWORD: password  # Replace with your desired password
      POSTGRES_DB: my_database     # Replace with your desired database name
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent data storage

  rust_web_server:
    build:
      context: . # Path to your Rust server source code
      dockerfile: Dockerfile      # Dockerfile to build the Rust application
    container_name: rust_server
    restart: always
    ports:
      - "8080:8080"  # Exposes your Rust web server on port 8080
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/my_database
      RUST_LOG: debug
    depends_on:
      - postgres  # Ensures the database service starts before the Rust server

volumes:
  postgres_data:
